/*
 * Service Problem Management
 * ## TMF API Reference: TMF656 - Service Problem Management  ### Release : 18.5 - December 2018  Service Problem Management API goal is to provide the ability to manage problems in the Service domain.   ### Resource  - serviceProblem  ### Operations Service Problem Management API performs the following operations on the resource : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity (for administration purposes) - Manage notification of events
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ServiceProblemRef;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Task resource that requests Service Problems to be ungrouped from a parent Skipped properties: id,href
 */
@ApiModel(description = "Task resource that requests Service Problems to be ungrouped from a parent Skipped properties: id,href")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-06T18:52:03.826Z")
public class ProblemUngroupCreate {
  @SerializedName("childProblem")
  private List<ServiceProblemRef> childProblem = new ArrayList<ServiceProblemRef>();

  @SerializedName("parentProblem")
  private ServiceProblemRef parentProblem = null;

  @SerializedName("@baseType")
  private String baseType = null;

  @SerializedName("@schemaLocation")
  private String schemaLocation = null;

  @SerializedName("@type")
  private String type = null;

  public ProblemUngroupCreate childProblem(List<ServiceProblemRef> childProblem) {
    this.childProblem = childProblem;
    return this;
  }

  public ProblemUngroupCreate addChildProblemItem(ServiceProblemRef childProblemItem) {
    this.childProblem.add(childProblemItem);
    return this;
  }

   /**
   * List of problems to be ungrouped from a parent problem
   * @return childProblem
  **/
  @ApiModelProperty(required = true, value = "List of problems to be ungrouped from a parent problem")
  public List<ServiceProblemRef> getChildProblem() {
    return childProblem;
  }

  public void setChildProblem(List<ServiceProblemRef> childProblem) {
    this.childProblem = childProblem;
  }

  public ProblemUngroupCreate parentProblem(ServiceProblemRef parentProblem) {
    this.parentProblem = parentProblem;
    return this;
  }

   /**
   * The parent problem from which the problems are to be ungrouped
   * @return parentProblem
  **/
  @ApiModelProperty(required = true, value = "The parent problem from which the problems are to be ungrouped")
  public ServiceProblemRef getParentProblem() {
    return parentProblem;
  }

  public void setParentProblem(ServiceProblemRef parentProblem) {
    this.parentProblem = parentProblem;
  }

  public ProblemUngroupCreate baseType(String baseType) {
    this.baseType = baseType;
    return this;
  }

   /**
   * When sub-classing, this defines the super-class
   * @return baseType
  **/
  @ApiModelProperty(value = "When sub-classing, this defines the super-class")
  public String getBaseType() {
    return baseType;
  }

  public void setBaseType(String baseType) {
    this.baseType = baseType;
  }

  public ProblemUngroupCreate schemaLocation(String schemaLocation) {
    this.schemaLocation = schemaLocation;
    return this;
  }

   /**
   * A URI to a JSON-Schema file that defines additional attributes and relationships
   * @return schemaLocation
  **/
  @ApiModelProperty(value = "A URI to a JSON-Schema file that defines additional attributes and relationships")
  public String getSchemaLocation() {
    return schemaLocation;
  }

  public void setSchemaLocation(String schemaLocation) {
    this.schemaLocation = schemaLocation;
  }

  public ProblemUngroupCreate type(String type) {
    this.type = type;
    return this;
  }

   /**
   * When sub-classing, this defines the sub-class entity name
   * @return type
  **/
  @ApiModelProperty(value = "When sub-classing, this defines the sub-class entity name")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProblemUngroupCreate problemUngroupCreate = (ProblemUngroupCreate) o;
    return Objects.equals(this.childProblem, problemUngroupCreate.childProblem) &&
        Objects.equals(this.parentProblem, problemUngroupCreate.parentProblem) &&
        Objects.equals(this.baseType, problemUngroupCreate.baseType) &&
        Objects.equals(this.schemaLocation, problemUngroupCreate.schemaLocation) &&
        Objects.equals(this.type, problemUngroupCreate.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(childProblem, parentProblem, baseType, schemaLocation, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProblemUngroupCreate {\n");
    
    sb.append("    childProblem: ").append(toIndentedString(childProblem)).append("\n");
    sb.append("    parentProblem: ").append(toIndentedString(parentProblem)).append("\n");
    sb.append("    baseType: ").append(toIndentedString(baseType)).append("\n");
    sb.append("    schemaLocation: ").append(toIndentedString(schemaLocation)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

