/*
 * Service Problem Management
 * ## TMF API Reference: TMF656 - Service Problem Management  ### Release : 18.5 - December 2018  Service Problem Management API goal is to provide the ability to manage problems in the Service domain.   ### Resource  - serviceProblem  ### Operations Service Problem Management API performs the following operations on the resource : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity (for administration purposes) - Manage notification of events
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.EventSubscription;
import io.swagger.client.model.EventSubscriptionInput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EventsSubscriptionApi
 */
@Ignore
public class EventsSubscriptionApiTest {

    private final EventsSubscriptionApi api = new EventsSubscriptionApi();

    
    /**
     * Register a listener
     *
     * Sets the communication endpoint address the service instance must use to deliver information about its health state, execution state, failures and metrics.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registerListenerTest() throws ApiException {
        EventSubscriptionInput data = null;
        EventSubscription response = api.registerListener(data);

        // TODO: test validations
    }
    
    /**
     * Unregister a listener
     *
     * Resets the communication endpoint address the service instance must use to deliver information about its health state, execution state, failures and metrics.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void unregisterListenerTest() throws ApiException {
        String id = null;
        api.unregisterListener(id);

        // TODO: test validations
    }
    
}
