/*
 * Service Problem Management
 * ## TMF API Reference: TMF656 - Service Problem Management  ### Release : 18.5 - December 2018  Service Problem Management API goal is to provide the ability to manage problems in the Service domain.   ### Resource  - serviceProblem  ### Operations Service Problem Management API performs the following operations on the resource : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity (for administration purposes) - Manage notification of events
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.EventSubscription;
import io.swagger.client.model.ServiceProblemAttributeValueChangeNotification;
import io.swagger.client.model.ServiceProblemCreateNotification;
import io.swagger.client.model.ServiceProblemInformationRequiredNotification;
import io.swagger.client.model.ServiceProblemStateChangeNotification;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NotificationListenersClientSideApi
 */
@Ignore
public class NotificationListenersClientSideApiTest {

    private final NotificationListenersClientSideApi api = new NotificationListenersClientSideApi();

    
    /**
     * Client listener for entity ServiceProblemAttributeValueChangeNotification
     *
     * Example of a client listener for receiving the notification ServiceProblemAttributeValueChangeNotification
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listenToServiceProblemAttributeValueChangeNotificationTest() throws ApiException {
        ServiceProblemAttributeValueChangeNotification data = null;
        EventSubscription response = api.listenToServiceProblemAttributeValueChangeNotification(data);

        // TODO: test validations
    }
    
    /**
     * Client listener for entity ServiceProblemCreateNotification
     *
     * Example of a client listener for receiving the notification ServiceProblemCreateNotification
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listenToServiceProblemCreateNotificationTest() throws ApiException {
        ServiceProblemCreateNotification data = null;
        EventSubscription response = api.listenToServiceProblemCreateNotification(data);

        // TODO: test validations
    }
    
    /**
     * Client listener for entity ServiceProblemInformationRequiredNotification
     *
     * Example of a client listener for receiving the notification ServiceProblemInformationRequiredNotification
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listenToServiceProblemInformationRequiredNotificationTest() throws ApiException {
        ServiceProblemInformationRequiredNotification data = null;
        EventSubscription response = api.listenToServiceProblemInformationRequiredNotification(data);

        // TODO: test validations
    }
    
    /**
     * Client listener for entity ServiceProblemStateChangeNotification
     *
     * Example of a client listener for receiving the notification ServiceProblemStateChangeNotification
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listenToServiceProblemStateChangeNotificationTest() throws ApiException {
        ServiceProblemStateChangeNotification data = null;
        EventSubscription response = api.listenToServiceProblemStateChangeNotification(data);

        // TODO: test validations
    }
    
}
